// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO user_friend (
    uid1, uid2, friend_status
) VALUES (
    $1, $2, 'REQ_UID1'
)
`

type CreateFriendRequestParams struct {
	Uid1 uuid.UUID
	Uid2 uuid.UUID
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, createFriendRequest, arg.Uid1, arg.Uid2)
	return err
}

const createFriendstatusType = `-- name: CreateFriendstatusType :exec
CREATE TYPE friendstatus AS enum (
  'REQ_UID1',
  'REQ_UID2',
  'FRIEND'
)
`

func (q *Queries) CreateFriendstatusType(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createFriendstatusType)
	return err
}

const createUsersTable = `-- name: CreateUsersTable :exec
CREATE TABLE user_friend (
    id SERIAL PRIMARY KEY,
    uid1 uuid NOT NULL,
    uid2 uuid NOT NULL,
    friend_status friendstatus NOT NULL
)
`

func (q *Queries) CreateUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUsersTable)
	return err
}
