version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: friends
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.me
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  
volumes:
  postgresql_volume:
